apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodedemo-service
  name: {{ include "localstack.fullname" . }}-nodedemo-svc-{{ .Values.env_slug }} 
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31000
  selector:
    app: nodedemo-{{ .Values.env_slug }}
  type: NodePort
status:
  loadBalancer: {}


